let data = [
  {
    //object
    id: 0,
    title: '개발 없이 노션과 GA를 통해 웹사이트 제작부터 데이터',
    name: '박용호',
    content:
      '최근에 많은 회사에서 노션으로 웹사이트를 제작 및 운영하고 있습니다.\n노션을 사용할 줄 안다면 개발을 몰라도, 개발자가 없어도 누구나 쉽게 웹사이트를 만들 수 있으며, 여기에 GA를 연결한다면 내 페이지에 몇명이 왔는지, 페이지의 어떤 버튼을 클릭했는지, 어디서 이탈했는지에 대한 정보까지 수집 및 분석이 가능합니다.\n\n1) 노션에 입력하기\n\n노션에 웹사이트에 표시될 내용을 입력합니다. 코딩으로 치면, html코드를 넣는것과 같은 방법입니다. 여기에 넣은 텍스트와 이미지들이 웹사이트에 그대로 나오게 됩니다.\n노션을 얼마나 잘 사용하는가?, 디자인 실력이 얼마나 뛰어난가?에 따라서 웹사이트의 퀄리티가 달라지지만, 연습을 통해 커버 가능한 부분이니 걱정할 필요는 없습니다.\n\n2) 노션 → 우피 연결하기\n\n우피라는 사이트에 접속하여 노션을 웹사이트화 합니다. 우피에 접속하여, 우피에게 노션 페이지 링크 전달을 통해 웹사이트화가 가능합니다.\n웹사이트로 만들고 싶은 노션 페이지에 접속한 후, 우측 상단의 공유를 클릭합니다. 웹에서 공유를 활성화한 후, 복사 버튼을 클릭하면 페이지 링크가 복사됩니다.\n\n3) 웹사이트 → GA 연결\n\nGA에서 좌측 하단의 설정 아이콘을 클릭하면, 관리 페이지로 이동할 수 있습니다. 가운데 속성 영역에서 데이터 스트림을 클릭합니다.\n웹사이트 URL 입력란에 GA와 연결하고자 한 랜딩 페이지 즉, 우피로 생성한 웹사이트의 “도메인”을 입력합니다.\n이제 생성된 스트림의 세부 정보를 확인합니다. 여기에 측정 ID 옆의 복사 아이콘을 클릭하면, ID 값이 복사됩니다. 복사한 측정 ID를 활용해 랜딩 페이지와 GA를 연결할 수 있습니다.\n다시 우피 콘솔창에 접속합니다. 우피는 자체 플러그인 기능을 통해 쉽게 GA를 연결할 수 있게 합니다. 플러그인 창 탭을 클릭하면, 플러그인 설정 창이 나옵니다. 여기서 Google Analytics 입력란에 방금 복사한 “측정 ID”를 붙여 넣고, 저장합니다.\n\n노션을 통한 사이트 제작부터, GA 연결까지의 과정을 통해, 기본적인 웹사이트 제작 방법 및 GA연결 방법을 알아보았습니다. 노션을 더 잘사용한다면, 더 복잡하고 멋진 웹사이트 제작이 가능하고, GA를 잘 다룬다면 몇명의 어떤 유저가 페이지에서 어떤 행동을 하는지 모든 분석이 가능합니다.',
    imgURL: '',
    hashTag: '',
    mainJob: '프론트엔드',
    date: '2023.05.09',
  },
  {
    id: 1,
    title: '[외부글] 컬리의 기업가치가 여전히 3조 원인 이유',
    name: '나윤재',
  },
  {
    id: 2,
    title:
      ' [외부글] 시장 세분화를 처음 시작할 때 자주 하는 질문 5가지 -    오픈서베이 블로그',
    content: ' 임영훈',
  },
];
//  이미지 URL , 해시태그 , 내용
let projectData = [
  {
    id: 0,
    title: ' [서울] 미술 작품 거래 차트 서비스',
    name: '박용호',
    content:
      '안녕하세요.  \n\n\n\n\n 특정장소에 대한 실시간 정보거래 서비스를 개발하고자 합니다.\n  올해 23년 창업진흥원 예비창업패키지 서류전형을 통과했고, 지금은 사업기획에서 조금 정비중에 있습니다.    현재 시드투자 유치를 위해서 VC와 1차 미팅을 가진 상태이고, 사업기획과 UX/UI 디자인이 완료되는데로 VC와 2차 미팅을 가질 예정입니다.  \n  올해 가을이 오기전에 시드 투자 유치를 하고 법인을 설립하여 운영하는것을 목표로 하고 있어요~^^ \t   프로젝트 인원은 8명이고, 진행 정도에 따라 필요 인원은 추가로 증원하는것을 생각하고 있습니다.\n',
    job: ['프론트엔드', '벡엔드', 'UX/UI기획'],
    requireJob: [2, 0, 1, 1],
    nowJob: [2, 1, 1],
    skill: ['javascript', 'react', 'java'],
    imgURL: 'main1',
    region: '서울',
    startDate: '2023-05-05',
    endDate: '2023-10-10',
  },
  {
    id: 1,
    title: ' [서울] 미술 작품 거래 차트 서비스',
    name: '나윤재',
    content:
      '안녕하세요.  \n\n\n\n\n 특정장소에 대한 실시간 정보거래 서비스를 개발하고자 합니다.\n  올해 23년 창업진흥원 예비창업패키지 서류전형을 통과했고, 지금은 사업기획에서 조금 정비중에 있습니다.    현재 시드투자 유치를 위해서 VC와 1차 미팅을 가진 상태이고, 사업기획과 UX/UI 디자인이 완료되는데로 VC와 2차 미팅을 가질 예정입니다.  \n  올해 가을이 오기전에 시드 투자 유치를 하고 법인을 설립하여 운영하는것을 목표로 하고 있어요~^^ \t   프로젝트 인원은 8명이고, 진행 정도에 따라 필요 인원은 추가로 증원하는것을 생각하고 있습니다.\n',
    job: ['프론트엔드', '벡엔드', 'UX/UI기획'],
    requireJob: [2, 0, 1, 1],
    nowJob: [2, 1, 1],
    skill: ['javascript', 'react', 'java'],
    imgURL: 'main1',
    region: '서울',
    startDate: '2023-05-05',
    endDate: '2023-10-10',
  },
  {
    id: 2,
    title: ' [서울] 미술 작품 거래 차트 서비스',
    name: '임영훈',
    content:
      '안녕하세요.  \n\n\n\n\n 특정장소에 대한 실시간 정보거래 서비스를 개발하고자 합니다.\n  올해 23년 창업진흥원 예비창업패키지 서류전형을 통과했고, 지금은 사업기획에서 조금 정비중에 있습니다.    현재 시드투자 유치를 위해서 VC와 1차 미팅을 가진 상태이고, 사업기획과 UX/UI 디자인이 완료되는데로 VC와 2차 미팅을 가질 예정입니다.  \n  올해 가을이 오기전에 시드 투자 유치를 하고 법인을 설립하여 운영하는것을 목표로 하고 있어요~^^ \t   프로젝트 인원은 8명이고, 진행 정도에 따라 필요 인원은 추가로 증원하는것을 생각하고 있습니다.\n',
    job: ['프론트엔드', '벡엔드', 'UX/UI기획'],
    requireJob: [2, 0, 1, 1],
    nowJob: [2, 1, 1],
    skill: ['javascript', 'react', 'java'],
    imgURL: 'main1',
    region: '서울',
    startDate: '2023-05-05',
    endDate: '2023-10-10',
  },
  {
    id: 3,
    title: ' [서울] 미술 작품 거래 차트 서비스',
    name: '우주은',
    content:
      '안녕하세요.  \n\n\n\n\n 특정장소에 대한 실시간 정보거래 서비스를 개발하고자 합니다.\n  올해 23년 창업진흥원 예비창업패키지 서류전형을 통과했고, 지금은 사업기획에서 조금 정비중에 있습니다.    현재 시드투자 유치를 위해서 VC와 1차 미팅을 가진 상태이고, 사업기획과 UX/UI 디자인이 완료되는데로 VC와 2차 미팅을 가질 예정입니다.  \n  올해 가을이 오기전에 시드 투자 유치를 하고 법인을 설립하여 운영하는것을 목표로 하고 있어요~^^ \t   프로젝트 인원은 8명이고, 진행 정도에 따라 필요 인원은 추가로 증원하는것을 생각하고 있습니다.\n',
    job: ['프론트엔드', '벡엔드', 'UX/UI기획'],
    requireJob: [2, 0, 1, 1],
    nowJob: [2, 1, 1],
    skill: ['javascript', 'react', 'java'],
    imgURL: 'main1',
    region: '서울',
    startDate: '2023-05-05',
    endDate: '2023-10-10',
  },
];
//내용 이미지URL , 해시태그,  지역, 총직무수, 현재 직무수 ,직무 ,요구경력
let developerData = [
  {
    id: 0,
    name: ' 박용호',
    mainJob: '프론트엔드 ',
    subJob: '벡엔드 ',
    job: '[a,b]',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    skill: ['javascript', 'react', 'java'],
    likeCount: '1',
  },
  {
    id: 1,
    name: ' 나윤재',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 1개 있습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    skill: 'javascript',
    likeCount: '1',
  },
  {
    id: 2,
    name: ' 임영훈',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 없습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    skill: 'javascript',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    likeCount: '1',
  },
  {
    id: 3,
    name: '우주은',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 없습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    skill: 'javascript',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    likeCount: '1',
  },
];
//경력 ,지역
export { data, projectData, developerData };
