let data = [
  {
    id: 0,
    title: ' [정보]개발 없이 노션과 GA를 통해 웹사이트 제작부터 데이터',
    name: '박용호',
    content: '글내용',
    imgURL: '',
    hashTag: '',
  },
  {
    id: 1,
    title: '[외부글] 컬리의 기업가치가 여전히 3조 원인 이유',
    content: '나윤재',
  },
  {
    id: 2,
    title:
      ' [외부글] 시장 세분화를 처음 시작할 때 자주 하는 질문 5가지 -    오픈서베이 블로그',
    content: ' 임영훈',
  },
];
//  이미지 URL , 해시태그 , 내용
let projectData = [
  {
    id: 0,
    title: ' [서울] 미술 작품 거래 차트 서비스',
    content: '박용호',
  },
  {
    id: 1,
    title: '문화예술 서비스 Art-on 프로젝트',
    content: '나윤재',
  },
  {
    id: 2,
    title: ' [서울] [직장인들을 위한 플랫폼 만들어봐요]',
    content: ' 임영훈',
    id: 3,
    title: ' [서울] [직장인들을 위한 플랫폼 만들어봐요]',
    content: ' 임영훈',
    id: 4,
    title: ' [서울] [직장인들을 위한 플랫폼 만들어봐요]',
    region: '',
    content: ' 임영훈',
    name: '',
    //content:'
    job: '',
    requireJob: '',
    nowJob: '',
    career: '',
    imgURL: '',
    hashTag: '',
  },
];
//내용 이미지URL , 해시태그,  지역, 총직무수, 현재 직무수 ,직무 ,요구경력
let developerData = [
  {
    id: 0,
    name: ' 박용호',
    mainJob: '프론트엔드 ',
    subJob: '벡엔드 ',
    project: '참여중인 프로젝트 2개 있습니다.',
    job: '[a,b]',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    skill: 'javascript',
    likeCount: '1',
  },
  {
    id: 1,
    name: ' 나윤재',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 1개 있습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    skill: 'javascript',
    likeCount: '1',
  },
  {
    id: 2,
    name: ' 임영훈',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 없습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    skill: 'javascript',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    likeCount: '1',
  },
  {
    id: 3,
    name: '우주은',
    mainJob: ' 프론트엔드 ',
    subJob: ' 벡엔드 ',
    project: '참여중인 프로젝트 없습니다.',
    career: '초보',
    region: '경기도',
    projectCount: '1',
    urlGithub: 'https://github.com/ParkYongHo1',
    skill: 'javascript',
    urlInsta: 'https://www.instagram.com/pxxk._.h0/?next=%2Fstudy._ho%2F',
    introduce: '안녕하세요 프론트엔드를 꿈꾸는 박용호 입니다.',
    likeCount: '1',
  },
];
//경력 ,지역
export { data, projectData, developerData };
